"""
Local Python bridge between the Streamlit frontend and the EXISTING
validation / advisor logic.

There is NO FastAPI / HTTP dependency here anymore:

    Streamlit  ->  this module  ->  backend.app.orchestrator
                                ->  backend.app.advisor
                                ->  existing agents

No validation logic is duplicated â€” everything delegates to the
existing backend implementations.
"""

import sys
from pathlib import Path

# ------------------------------------------------------------------
# Make the existing backend importable
# ------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[1]
BACKEND_DIR = PROJECT_ROOT / "backend"

if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

# Load backend secrets (.env) so the agents can reach their LLMs,
# without touching or duplicating any backend code.
try:
    from dotenv import load_dotenv
    load_dotenv(BACKEND_DIR / ".env")
except ImportError:
    pass


class BackendError(Exception):
    """Raised when the validation pipeline cannot run."""


def _get_orchestrator():
    """Import the existing orchestrator lazily (heavy imports)."""
    try:
        from app.orchestrator import run_startup_validation
        return run_startup_validation
    except Exception as exc:
        raise BackendError(
            f"Could not load the validation pipeline: {exc}"
        ) from exc


def _get_advisor():
    """Import the existing advisor lazily."""
    try:
        from app.advisor import ask_advisor
        return ask_advisor
    except Exception as exc:
        raise BackendError(
            f"Could not load the AI Advisor: {exc}"
        ) from exc


def build_validate_payload(
    idea: str,
    country: str = "",
    location: str = "",
    budget: str = "",
    industry: str = "",
    currency: str = "",
) -> str:
    """
    Compose the startup idea text from the form inputs.

    The existing pipeline takes a single idea string, so the optional
    context fields are appended to it rather than dropped.
    """
    parts = [idea.strip()]
    meta = []
    if industry:
        meta.append(f"Industry: {industry}")
    if country:
        meta.append(f"Country: {country}")
    if location:
        meta.append(f"Location: {location}")
    if budget:
        # Currency is country-aware (India -> INR, USA -> USD, ...).
        # No currency code is appended when the country is unknown/empty —
        # the amount must never be silently labelled USD.
        meta.append(f"Budget: {budget} {currency}" if currency else f"Budget: {budget}")
    if meta:
        parts.append("(" + "; ".join(meta) + ")")
    return "\n".join(parts)


def validate_startup(
    idea: str,
    country: str = "",
    location: str = "",
    budget: str = "",
    industry: str = "",
    currency: str = "",
) -> dict:
    """
    Run the EXISTING validation pipeline directly and return the
    shared_state dict it produces (unchanged shape).
    """
    composed_idea = build_validate_payload(
        idea, country, location, budget, industry, currency
    )
    try:
        return _get_orchestrator()(composed_idea)
    except BackendError:
        raise
    except Exception as exc:
        raise BackendError(f"The validation pipeline failed: {exc}") from exc


def ask_advisor(
    question: str,
    validation_response: dict | None = None,
    conversation_history: list | None = None,
) -> dict:
    """
    Ask the EXISTING conversational advisor a question about the
    completed validation. Normal request/response â€” no streaming.

    Returns {"answer": "<text>"}.
    """
    if not validation_response:
        raise BackendError("Please run a validation first.")

    advisor_fn = _get_advisor()
    try:
        raw = advisor_fn(
            question,
            validation_response,
            conversation_history=conversation_history or [],
        )
    except Exception as exc:
        raise BackendError(f"The advisor failed: {exc}") from exc

    # The existing advisor returns a plain string answer.
    return {"answer": str(raw)}


def download_pdf(pdf_path: str) -> bytes:
    """
    Return the bytes of a PDF already generated by the EXISTING
    pipeline (see backend/app/pdf_generator.py). No HTTP involved.
    """
    if not pdf_path:
        raise BackendError("No PDF was generated for this validation.")
    pdf_file = Path(pdf_path)
    if not pdf_file.is_absolute():
        pdf_file = PROJECT_ROOT / pdf_file
    if not pdf_file.exists():
        raise BackendError(f"Report PDF not found: {pdf_file}")
    return pdf_file.read_bytes()


def health_check() -> dict:
    """Lightweight liveness probe -- kept for API compatibility."""
    return {"status": "ok"}


