import sys
from pathlib import Path

# ==================================================
# PATH SETUP
# ==================================================

sys.path.append(
    str(Path(__file__).resolve().parents[1])
)

# ==================================================
# IMPORTS
# ==================================================

from deepagents import create_deep_agent

from app.config import gemini_model_2
from agents.subagents.market_analysis import market_subagent

# ==================================================
# CREATE DEEP AGENT
# ==================================================

agent = create_deep_agent(

    model=gemini_model_2,

    subagents=[
        market_subagent
    ]

)

# ==================================================
# USER INPUT
# ==================================================

idea = input("Enter Startup Idea: ")

# ==================================================
# INVOKE AGENT
# ==================================================

result = agent.invoke(

    {
        "messages": [
            {
                "role": "user",
                "content": f"""
Startup Idea:

{idea}

Perform ONLY market analysis.

Delegate ONLY to market_agent.

Return ONLY the JSON generated by market_agent.
"""
            }
        ]
    }

)

# ==================================================
# OUTPUT
# ==================================================

print("\nRESULT\n")

import json

response = result["messages"][-1].content

if isinstance(response, list):
    response = response[0]["text"]

try:
    parsed = json.loads(response)
    print(json.dumps(parsed, indent=4))
except Exception:
    print(response)